FROM node:20

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./
COPY package.json ./

COPY apps/backend/package.json ./
WORKDIR /app

RUN pnpm install --filter ./apps/backend...

COPY apps/backend backend

WORKDIR /app/apps/backend

RUN pnpm run prisma-generate


RUN pnpm run build 

EXPOSE 3333

CMD [ "pnpm", "run", "start:prod" ]
