version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
